/** Pathway-detail hero slides (full-width slider, same pattern as home). */

import type { HomeHeroSlide } from '@/content/homeHeroStage';
import type { PathwaySlug } from '@/content/owwPublicContent';

export const PATHWAY_HERO_SLIDES: Record<PathwaySlug, HomeHeroSlide[]> = {
  career: [
    {
      id: 'career-explore',
      kicker: 'Start a career',
      title: 'See the full path from first interest to licensed work',
      body: 'Explore treatment, distribution, lab, engineering, and leadership roles—then match your skills to openings across New York.',
      imageSrc: '/home/stage/oww-careers.jpg',
      imageAlt: 'Workforce participants touring a water treatment plant control room',
      ctaLabel: 'Browse jobs',
      ctaHref: '/{state}/jobs',
    },
    {
      id: 'career-quality',
      kicker: 'Laboratory & water quality',
      title: 'Protect every tap with sampling and analysis skills',
      body: 'Water quality careers verify turbidity, residuals, and contaminants so communities can trust what reaches their homes.',
      imageSrc: '/home/stage/lab-testing.jpg',
      imageAlt: 'Water quality analyst testing drinking water samples in a laboratory',
      ctaLabel: 'Express interest',
      ctaHref: '/{state}/interest?pathway=career',
    },
    {
      id: 'career-ops',
      kicker: 'Treatment operations',
      title: 'Plant operations that keep systems running every shift',
      body: 'Clarifiers, filters, and distribution work depend on skilled operators—OWW connects you to training, certification prep, and hiring partners.',
      imageSrc: '/home/stage/treatment-plant.jpg',
      imageAlt: 'Municipal drinking water treatment plant filtration basins',
      ctaLabel: 'Create account',
      ctaHref: '/login',
    },
  ],
  hire: [
    {
      id: 'hire-workforce',
      kicker: 'Hire with WW360 + OWW',
      title: 'Staff utilities before gaps become emergencies',
      body: 'Document operators, training, and upcoming vacancies—then recruit ready-now and transferable talent on the same taxonomy candidates use.',
      imageSrc: '/home/stage/ww360.jpg',
      imageAlt: 'Utility manager reviewing workforce and training dashboards',
      ctaLabel: 'Create employer account',
      ctaHref: '/login',
    },
    {
      id: 'hire-ops',
      kicker: 'Plant & field roles',
      title: 'Post openings that match real plant and field work',
      body: 'From treatment plants to distribution crews, publish criteria that surface exact and transferable matches—not keyword noise.',
      imageSrc: '/home/stage/treatment-plant.jpg',
      imageAlt: 'Municipal drinking water treatment plant',
      ctaLabel: 'View job board',
      ctaHref: '/{state}/jobs',
    },
    {
      id: 'hire-env',
      kicker: 'Wastewater & environment',
      title: 'Protect receiving waters with a ready bench',
      body: 'Wastewater operators safeguard fishable, swimmable waters. Use OWW to recruit, message applicants, and report hiring outcomes.',
      imageSrc: '/home/stage/wastewater.jpg',
      imageAlt: 'Wastewater treatment aeration basin',
      ctaLabel: 'Express hiring interest',
      ctaHref: '/{state}/interest?pathway=hire',
    },
  ],
  educate: [
    {
      id: 'educate-field',
      kicker: 'Educators & trainers',
      title: 'Connect classrooms to source-to-tap careers',
      body: 'Share watershed science, operator pathways, and Gold Standard training so students see water as a public-service career—not only a textbook topic.',
      imageSrc: '/home/stage/source-sampling.jpg',
      imageAlt: 'Operator sampling reservoir water for quality monitoring',
      ctaLabel: 'Submit a program',
      ctaHref: '/{state}/programs/submit',
    },
    {
      id: 'educate-lab',
      kicker: 'Lab & STEM pathways',
      title: 'Lab skills that transfer into utility careers',
      body: 'Sampling, analysis, and compliance monitoring are natural bridges from STEM programs into water quality and operator tracks.',
      imageSrc: '/home/stage/lab-testing.jpg',
      imageAlt: 'Laboratory testing of drinking water samples',
      ctaLabel: 'Browse career areas',
      ctaHref: '/{state}/career',
    },
    {
      id: 'educate-tour',
      kicker: 'Plant tours & awareness',
      title: 'Bring learners onto the plant floor',
      body: 'Tours, microvideos, and partner curricula help educators show what a day in water really looks like—from GED pathways to advanced degrees.',
      imageSrc: '/home/stage/oww-careers.jpg',
      imageAlt: 'Participants touring a treatment plant',
      ctaLabel: 'Express interest',
      ctaHref: '/{state}/interest?pathway=educate',
    },
  ],
  ambassador: [
    {
      id: 'ambassador-story',
      kicker: 'Ambassadors',
      title: 'Champion water careers in your community',
      body: 'Share credible workforce facts, host career conversations, and connect people into the four pathways that keep New York’s water systems staffed.',
      imageSrc: '/home/stage/wastewater.jpg',
      imageAlt: 'Wastewater treatment protecting receiving waters',
      ctaLabel: 'Become an ambassador',
      ctaHref: '/{state}/interest?pathway=ambassador',
    },
    {
      id: 'ambassador-source',
      kicker: 'Source water & public trust',
      title: 'Help the public see why staffing capacity matters',
      body: 'From reservoirs to rivers, ambassadors make the case that qualified people are as critical as capital investment.',
      imageSrc: '/home/stage/source-sampling.jpg',
      imageAlt: 'Clear reservoir water sampling',
      ctaLabel: 'Ambassador pathway',
      ctaHref: '/{state}/ambassador',
    },
    {
      id: 'ambassador-outreach',
      kicker: 'Schools & civic groups',
      title: 'Carry the message where careers begin',
      body: 'Use toolkits and microvideos in schools, civic groups, and legislative conversations so the next generation finds water work.',
      imageSrc: '/home/stage/oww-careers.jpg',
      imageAlt: 'Workforce outreach at a treatment facility',
      ctaLabel: 'Express interest',
      ctaHref: '/{state}/interest?pathway=ambassador',
    },
  ],
};
