/** Static fallback pathway hero slides when the API is empty/unreachable. */

import type { HomeHeroSlide } from '@/content/homeHeroStage';
import type { PathwaySlug } from '@/content/owwPublicContent';

export const PATHWAY_HERO_SLIDES: Record<PathwaySlug, HomeHeroSlide[]> = {
  career: [
    {
      id: 'career-1',
      scope: 'career',
      kicker: 'Explore careers',
      title: 'Six career areas, one statewide job board',
      body: 'Treatment, distribution, lab, engineering, technology, and leadership—browse openings that keep New York’s water systems running.',
      imageSrc: '/pathways/stage/career-1.jpg',
      imageAlt: 'Utility field crew in high-visibility vests working at a distribution hydrant',
      ctaLabel: 'Browse jobs',
      ctaHref: '/{state}/jobs',
    },
    {
      id: 'career-2',
      scope: 'career',
      kicker: 'Get matched',
      title: 'Tell us your skills; see Ready now and transferable matches',
      body: 'Complete the matching questionnaire so employers see career changers and Ready now talent on the same taxonomy.',
      imageSrc: '/pathways/stage/career-2.jpg',
      imageAlt: 'Career changer at a laptop in a treatment plant control room',
      ctaLabel: 'Express interest',
      ctaHref: '/{state}/interest?pathway=career',
    },
    {
      id: 'career-3',
      scope: 'career',
      kicker: 'Train and certify',
      title: 'Gold Standard operator training from GED to PhD',
      body: 'Connect to OWW/B&L training, NYSDOH-approved courses, and certification prep so you can move from interest to licensed work.',
      imageSrc: '/pathways/stage/career-3.jpg',
      imageAlt: 'Instructor and students in a hands-on operator training lab',
      ctaLabel: 'Create account',
      ctaHref: '/login',
    },
  ],
  hire: [
    {
      id: 'hire-1',
      scope: 'hire',
      kicker: 'Recruit on the shared taxonomy',
      title: 'Post openings that surface exact and transferable matches',
      body: 'Describe required vs trainable credentials so Ready now and Strong transferable candidates find your roles—not keyword noise.',
      imageSrc: '/pathways/stage/hire-1.jpg',
      imageAlt: 'Utility HR manager reviewing candidate profiles on a monitor',
      ctaLabel: 'Register as utility admin',
      ctaHref: '/register/utility',
    },
    {
      id: 'hire-2',
      scope: 'hire',
      kicker: 'Plan the bench',
      title: 'See 30-day to 3-year staffing needs before vacancies hit',
      body: 'Pair WW360 succession planning with OWW recruiting so mentoring and hiring start before gaps become emergencies.',
      imageSrc: '/pathways/stage/hire-2.jpg',
      imageAlt: 'Supervisor and senior operator walking a treatment plant gallery',
      ctaLabel: 'Express interest',
      ctaHref: '/{state}/interest?pathway=hire',
    },
    {
      id: 'hire-3',
      scope: 'hire',
      kicker: 'Close the loop',
      title: 'Report hires that feed statewide workforce analytics',
      body: 'Track applicants, interviews, and hiring outcomes that roll into NYSAWWA engagement reporting for grants, boards, and legislators.',
      imageSrc: '/pathways/stage/hire-3.jpg',
      imageAlt: 'New operator receiving a handshake and badge at a plant gate',
      ctaLabel: 'Employer sign-in',
      ctaHref: '/login',
    },
  ],
  educate: [
    {
      id: 'educate-1',
      scope: 'educate',
      kicker: 'List courses and events',
      title: 'Put training where candidates and utilities already look',
      body: 'Publish courses and events on your educator dashboard so learners discover them inside OWW—not only on scattered calendars.',
      imageSrc: '/pathways/stage/educate-1.jpg',
      imageAlt: 'Community college instructor teaching hydraulics at a whiteboard',
      ctaLabel: 'Submit a program',
      ctaHref: '/{state}/programs/submit',
    },
    {
      id: 'educate-2',
      scope: 'educate',
      kicker: 'Training Center partnership',
      title: 'Gold Standard certification and CEUs from Albany, Syracuse, Rochester',
      body: 'Point cohorts to OWW/B&L Gold Standard operator pathways and continuing education that utilities trust.',
      imageSrc: '/pathways/stage/educate-2.jpg',
      imageAlt: 'Hands-on operator training room with bench-scale treatment units',
      ctaLabel: 'Regional training',
      ctaHref: '/{state}/regional/training',
    },
    {
      id: 'educate-3',
      scope: 'educate',
      kicker: 'From cohort to hire',
      title: 'Send learners toward jobs and employer matches',
      body: 'Align programs to certification needs and help graduates move from interest to training to employment across New York.',
      imageSrc: '/pathways/stage/educate-3.jpg',
      imageAlt: 'Students on a plant tour with a guide pointing at a clarifier',
      ctaLabel: 'Express interest',
      ctaHref: '/{state}/interest?pathway=educate',
    },
  ],
  ambassador: [
    {
      id: 'ambassador-1',
      scope: 'ambassador',
      kicker: 'Make the case',
      title: 'Credible NY workforce facts for schools, boards, and legislators',
      body: 'Use statewide statistics—millions served, thousands of operators, aging workforce—to show why staffing capacity is as critical as capital investment.',
      imageSrc: '/pathways/stage/ambassador-1.jpg',
      imageAlt: 'Speaker presenting to a town board in a community meeting room',
      ctaLabel: 'Express interest',
      ctaHref: '/{state}/interest?pathway=ambassador',
    },
    {
      id: 'ambassador-2',
      scope: 'ambassador',
      kicker: 'Open doors',
      title: 'Share microvideos and pathway links with your network',
      body: 'Host career conversations and point people to Career, Hire, and Educate doorways with toolkits that stay current.',
      imageSrc: '/pathways/stage/ambassador-2.jpg',
      imageAlt: 'Retired operator mentoring a teen at a career fair table',
      ctaLabel: 'Share career pathway',
      ctaHref: '/{state}/career',
    },
    {
      id: 'ambassador-3',
      scope: 'ambassador',
      kicker: 'Connect partners',
      title: 'Loop in NYSAWWA when a school or utility wants more',
      body: 'Introduce utilities, schools, and local officials when a deeper partnership is needed—ambassadors multiply OWW’s reach.',
      imageSrc: '/pathways/stage/ambassador-3.jpg',
      imageAlt: 'Partners meeting at a reservoir overlook during a watershed visit',
      ctaLabel: 'Create account',
      ctaHref: '/login',
    },
  ],
};
